### ISSUE TITLE
Any model checkpoints available?

### ISSUE THREAD

**Issue by haorannlp** [layer6ai-labs/CMLMC#1]
Hi! Would you mind sharing the model checkpoints for EN-DE, DE-EN, EN-RO, RO-EN? Thanks

**Comment by risingdhxs** [comment]
Hi~ Due to a few different reasons we won't be sharing the model checkpoints, sorry about that. But by grabbing the datasets and following the example training scripts they should be reproducible (we experimented quite a few times to ensure that before we made the code public).
